#!/bin/sh
date
export PS4=' $SECONDS + '
set -x

########################################
# SET THE WORKING DIRECTORY
########################################
export DATA=${DATA:-${DATAROOT:?}/$jobid}
mkdir -p $DATA
cd $DATA

####################################
# Specify NET Name and RUN
####################################
export NET=${NET:-spc_post}
export RUN=${RUN:-spc_post}
export pgmout="$$"

####################################
# SENDECF  - Flag Events on ECFLOW
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
####################################
export SENDCOM=${SENDCOM:-YES}
export SENDECF=${SENDECF:-YES}
export SENDDBN=${SENDDBN:-YES}

########################################
# SET THE EXECUTION VARIABLES
########################################
export FIXspc_post=${FIXspc_post:-${HOMEspc_post}/fix}
export USHspc_post=${USHspc_post:-${HOMEspc_post}/ush} 

########################################
# SET THE DATE VARIABLES
########################################
export cycle=t${cyc}z
setpdy.sh
. ./PDY

########################################
# SET THE INPUT DIRECTORIES
########################################
export COMOUT=${COMOUT:-$(compath.py -o $envir/com/$NET/${spc_post_ver})}
export COMOUTspc_post=${COMOUTspc_post:-${COMOUT}}
export COMOUTspc_nam=${COMOUTspc_nam:-${COMOUTspc_post}/spc_nam}
export COMOUTspc_pickle=${COMOUTspc_pickle:-${COMOUTspc_post}/spc_pickle}                     

export COMINhiresw=${COMINhiresw:-$(compath.py $envir/com/hiresw/${hiresw_ver})}
export COMINhrrr=${COMINhrrr:-$(compath.py $envir/com/hrrr/${hrrr_ver})}
export COMINnam=${COMINnam:-$(compath.py $envir/com/nam/${nam_ver})}
export COMINspcsref=${COMINspcsref:-$(compath.py $envir/com/spcsref/${spcsref_ver})}

export COMINhrw_string="fv3"

##############################################
# Execute the script
# The Calibrated Thunder has 00Z/12Z cycles, should launch at 02Z/14Z
# fhour =  1 .. 48 for thunder jobs
#         49 50 51 for thunder full jobs at 00Z
#         49 50    for thunder full jobs at 12Z
${HOMEspc_post}/scripts/exforecast_href_cal_thunder.sh
export err=$?; err_chk
##############################################

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg $jlogfile "$msg"

if [ -e $pgmout ]; then
    cat $pgmout
fi

########################################
# CLEAN UP THE WORKING DIRECTORY
########################################
if [ "$KEEPDATA" != "YES" ]; then
   rm -rf $DATA
fi

date

